### ISSUE TITLE
Implement google search/maps api

### ISSUE THREAD

**Issue by OscarNevarez** [coderwatch/demo-web-project#2]
Use both the google search and google maps API to get information of the persons current whereabouts.

**Comment by Philc90** [comment]
User Story: As a user, I want to be able to see suggestions for activities on a map so that I can decide which one I want to do.

**Comment by Philc90** [comment]
testMapsApi.html demos the addition of markers of places of interest to a Google Map. Given a latitude & longitude value for each place of interest it is possible to add a marker object for each one which will mark them on the map. Eventbrite and Yelp can be used to search for places to mark on the map. Also, the HTML5 geolocation API can be used to get the user's location as lat/long. This can be sent to the Eventbrite and Yelp APIs to get a better search.
